fix install check

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -26,15 +26,15 @@ do
 done
 [[ $1 ]] && list="$1"
 [[ $2 ]] && xz="$2.txz"
-[[ ! -f "$list" ]] && Help && echo "No backup list file $list present, EXITING" && exit 2
+[[ ! -f "$list" ]] && Help && echo "ABORT: no backup list file $list present" && exit 2
 rlist=$(readlink -e "$list")
 
-! >"$xz" && Help && echo "Can't write to backup file $xz, EXITING" && exit 3
-! >"$tar" && Help && echo "Can't write to temporary file $tar, EXITING" && exit 4
+! >"$xz" && Help && echo "ABORT: can't write to backup file $xz" && exit 3
+! >"$tar" && Help && echo "ABORT: can't write to temporary file $tar" && exit 4
 
 mapfile -t files <"$rlist"
 declare -i n_files=${#files[@]} n=0
-! tar cPf "$tar" "$rlist" && Help && echo "Cannot output to $tar, EXITING" && exit 5
+! tar cPf "$tar" "$rlist" && Help && echo "ABORT: cannot output to $tar" && exit 5
 echo -e "  Files and directories backed up to $xz:\nSCRIPT $self\nLIST $rlist"
 tar rhPf "$tar" "$self"
 
