Build stable by default, and git if requested

diff --git a/buildnano b/buildnano
--- a/buildnano
+++ b/buildnano
@@ -1,12 +1,12 @@
 #!/bin/bash
 
-# buildnano - Build nano from git repo on Ubuntu
-# Required: coreutils(mkdir cd) git autoconf autopoint automake pkg-config
-#   gettext libncursesw5-dev groff[optional html-help] texinfo make gcc
-#   libmagic-dev[optional filetype detection]
-
-# Location of git repos, can be passed in environment variable GITDIR
-gitdir=${GITDIR:=~/git}
+# buildnano - Build nano from source (stable relase or git repo) on Ubuntu
+# Required: coreutils(mkdir cd mktemp rm)
+#   git+autoconf+autopoint+automake/wget[git/release]
+#   pkg-config gettext libncursesw5-dev groff[optional html-help]
+#   texinfo make gcc libmagic-dev[optional filetype detection]
+# Usage: buildnano [-g|--git]
+#   -g/--git: build from current git HEAD (not stable release version)
 
 # Configuration options to (un)comment-out
 conf=(
@@ -32,8 +32,16 @@ conf=(
 	#disable-nls
 )
 
+# Location of git repos, can be passed in environment variable GITDIR
+gitdir=${GITDIR:=~/git}
 # URL of nano git repo
 nanogit="http://git.savannah.gnu.org/git/nano.git"
+
+# URL of latest release
+nanosrc="https://nano-editor.org/dist/latest/nano-3.2.tar.xz"
+
+# Required packages
+req="pkg-config libncursesw5-dev libmagic-dev texinfo gettext groff"
 
 
 Abort(){ # $1:message
@@ -56,33 +64,56 @@ then
 		Abort "package sudo required to elevate privilege for installing"
 fi
 
+git=0
+if [[ $1 ]]
+then
+	[[ $1 = -g || $1 = --git ]] && git=1 req+=" git autoconf autopoint" ||
+		Abort "argument can only be -r/--release"
+else
+	req+=" wget"
+fi
+
 # Install missing packages
+
 pkgs=$(dpkg -l) inst=
-for p in git autoconf autopoint pkg-config libncursesw5-dev libmagic-dev \
-		texinfo gettext groff
+for p in $req
 do grep -q "^ii  $p " <<<$pkgs || inst+=" $p"; done
 [[ $inst ]] && echo "Need to install $inst" &&
 	! Sudo apt-get install $inst && Abort "could not install packages:$inst"
 
-# Prepare git repo clone
-[[ ${gitdir:0:1} = / ]] || Abort "GITDIR not an absolute path: $gitdir"
-mkdir -p "$gitdir" || Abort "$gitdir not a directory"
-cd "$gitdir" || Abort "could not enter git directory $gitdir"
-
-# Pull when repo present already
-if [[ -d nano ]]
+if ((git))
 then
-	cd nano || Abort "could not enter directory $gitdir/nano"
-	# Delete on unsuccessful pull
-	! git pull && cd .. && rm -rf -- nano
+	# Prepare git repo clone
+	[[ ${gitdir:0:1} = / ]] || Abort "GITDIR not an absolute path: $gitdir"
+	mkdir -p "$gitdir" || Abort "$gitdir not a directory"
+	cd "$gitdir" || Abort "could not enter git directory $gitdir"
+
+	# Pull when repo present already
+	if [[ -d nano ]]
+	then
+		cd nano || Abort "could not enter directory $gitdir/nano"
+		# Delete on unsuccessful pull
+		! git pull && cd .. && rm -rf -- nano
+	fi
+	cd "$gitdir"
+	[[ ! -d nano ]] && ! git clone $nanogit &&
+		Abort "could not download the nano git repo"
+	cd nano
+else
+	# Build in temporary directory in PWD
+	tmpdir=$(mktemp -d "./nano.XXXXXX")
+	tmpdir=$(readlink -e "$tmpdir") here=$PWD
+	trap "cd '$here'; rm -rf -- '$tmpdir'" QUIT EXIT
+	cd "$tmpdir" || Abort "could not enter directory $tmpdir"
+	wget -q "$nanosrc" || Abort "could not download nano source archive"
+	file=${nanosrc##*/}
+	tar xf "$file" || Abort "could not unpack $file"
+	dir=${file%.tar.?z}
+	cd "$dir" || Abort "could not enter directory $tmpdir/$dir"
 fi
-cd "$gitdir"
-[[ ! -d nano ]] && ! git clone $nanogit &&
-	Abort "could not download the nano git repo"
-cd nano
 
 # Needs autoconf autopoint
-./autogen.sh || Abort "error in Autogen"
+((git)) && ! ./autogen.sh && Abort "error in Autogen"
 
 # Needs gcc pkg-config libncursesw5-dev gettext (groff)
 ./configure ${conf[@]/#/--} || Abort "error in Configure"
@@ -92,6 +123,6 @@ make || Abort "error in Make"
 
 # Needs make sudo
 Sudo make install-strip || Abort "error in Install"
-
 hash nano
+
 exit 0
