Change formatting and code style

diff --git a/difth b/difth
--- a/difth
+++ b/difth
@@ -1,7 +1,7 @@
 #!/bin/bash
 set +vx
 # difth - show the difference between 2 Thai language files in html or terminal
-## Required: swath dwdiff
+## Required: swath dwdiff sed coreutils(cat type mktemp rm)
 
 Help(){
 	cat <<-EOF
@@ -17,20 +17,15 @@ Help(){
 ! type -p dwdiff &>/dev/null && echo "ABORT: package dwdiff not installed" && exit 2
 [[ -z $2 ]] && Help && echo "ABORT: At least 2 filenames necessary" && exit 3
 [[ $4 ]] && Help && echo "ABORT: More than 3 arguments" && exit 4
-! ai=$(readlink -e "$1") && Help && echo "ABORT: First argument no file: $1" && exit 5
-! bi=$(readlink -e "$2") && Help && echo "ABORT: Second argument no file: $2" && exit 6
-at=$(tempfile)
-bt=$(tempfile)
-st=$(tempfile)
-#mapfile -t ia <"$1"
-#mapfile -t ib <"$2"
-	
-## separators that don't occur in the input files already..?
-s="{s$RANDOM}"
-w="{w$RANDOM}"
-x="{x$RANDOM}"
-y="{y$RANDOM}"
-z=$x
+#! ai=$(readlink -e "$1") && Help && echo "ABORT: First argument no file: $1" && exit 5
+#! bi=$(readlink -e "$2") && Help && echo "ABORT: Second argument no file: $2" && exit 6
+[[ ! -f $1 ]] && Help && echo "ABORT: First argument no file: $1" && exit 
+[[ ! -f $2 ]] && Help && echo "ABORT: Second argument no file: $2" && exit 6
+[[ $1 = $2 ]] && ai=$(readlink -e	"$1") bi=$(readlink -e "$2") || ai=$1 bi=$2
+tmp=$(mktemp -d) at="$tmp/at" bt="$tmp/bt" st="$tmp/st"
+
+## unique separators
+s="{s$RANDOM}" w="{w$RANDOM}" x="{x$RANDOM}" y="{y$RANDOM}" z=$x
 grep -e "$s" -e "$w" -e "$x" -e "$y" "$1" || grep -e "$s" -e "$w" -e "$x" -e "$y" "$2" &&
 	echo "ABORT: separator present in input files: $s $w $x $y" && exit 7
 
@@ -42,7 +37,6 @@ then
 ci=$(dwdiff -s -A best -d "$s" -w "$w" -x "$x" -y "$y" -z "$z" "$at" "$bt" 2>"$st" |
 		sed -e "s@$s@@g" -e 's@^@<br />@g' -e "s@$y@<span class=\"v\">@g"\
 				-e "s@$w@<span class=\"x\">@g" -e "s@$x@</span>@g")
-
 cat <<EOF >"$3"
 <html lang="th">
 <head>
@@ -84,17 +78,19 @@ window.onclick = function (){
 body {font-size:200%; font-family:Arundina,serif}
 span.x {background:pink; text-decoration:line-through}
 span.v {background:lightblue; text-decoration:underline}
-span.i {font-size:90%; font-weight:normal}
 div.b {background:darkgray; color:black}
 h1 {text-align:center; font-size: 80%}
 pre {margin-left:1em; font-weight:bold}
 div {background:white; padding:0.2em}
 </style>
 </head>
-<body>
-<div class="b"><h1><span class="x">$ai</span> <span class="v">$bi</span></h1>
-<pre>$(cat "$st")
-<span class="i">Click to cycle through the display modes: differences (pink+blue) / original (pink) / corrected (blue).</span></pre></div>
+<body title="Click to see: differences (pink+blue) / original (pink) / corrected (blue)">
+<div class="b">
+<h1><span class="x">$ai</span> <span class="v">$bi</span></h1>
+<pre>
+$(cat "$st")
+</pre>
+</div>
 <div>
 $ci
 </div>
@@ -106,10 +102,10 @@ else
 	ci=$(dwdiff -s -A best -d "$s" -w "$w" -x "$x" -y "$y" -z "$z" "$at" "$bt" 2>"$st" |sed -e "s@$s@@g" \
 			-e "s@$y@$(echo $'\o33\[7;4;31m')@g" -e "s@$w@$(echo $'\o33\[7;4;34m')@g" -e "s@$x@$(echo $'\o33\[0m')@g")
 	echo -e "$ci"
-	echo '---------------------------------------------------------------------------------------------------'
+	echo '--------------------------------------------------------------------------------'
 	cat "$st"
 fi
 
-rm -- "$at" "$bt" "$st"
+rm -r -- "$tmp"
 
 exit 0
