Add --nojs flag to difth

diff --git a/difth b/difth
--- a/difth
+++ b/difth
@@ -12,16 +12,18 @@ Help(){
 	cat <<-EOF
 		 $(basename $0) - Show the differences between 2 Thai language input files
 		  and either produce a html file, or output result to the terminal
-		 USAGE:  $0 <file1> <file2> [<html-out>]
+		 USAGE:  $0 [-n|--nojs] <file1> <file2> [<html-out>]
 		   file1 and file2 are mandatory, html-out is optional (otherwise to stdout)
-		   While viewing the html: click to cycle through the display modes.
+		   When -n or --nojs is given, no javascript is used for html, otherwise
+		   while viewing the html: click to cycle through the display modes.
 	EOF
 }
 
 ! type -p swath &>/dev/null && echo "ABORT: package swath not installed" && exit 1
 ! type -p dwdiff &>/dev/null && echo "ABORT: package dwdiff not installed" && exit 2
-[[ -z $2 ]] && Help && echo "ABORT: At least 2 filenames necessary" && exit 3
-[[ $4 ]] && Help && echo "ABORT: More than 3 arguments" && exit 4
+[[ $1 = -n || $1 = --nojs ]] && nojs=1 && shift || nojs=0
+(($#<2)) && Help && echo "ABORT: At least 2 filenames necessary" && exit 3
+(($#>3)) && Help && echo "ABORT: More than 3 arguments" && exit 4
 [[ ! -f $1 ]] && Help && echo "ABORT: First argument no file: $1" && exit 
 [[ ! -f $2 ]] && Help && echo "ABORT: Second argument no file: $2" && exit 6
 [[ $1 = $2 ]] && ai=$(readlink -e	"$1") bi=$(readlink -e "$2") || ai=$1 bi=$2
@@ -42,11 +44,16 @@ then  ## html
 	ci=$(dwdiff -s -R -A best -d $d -w $o -x $e -y $n -z $e "$at" "$bt" 2>"$st" |\
 		sed -e "s@$d@@g" -e 's@^@<br />@g' -e "s@$e@</span>@g"\
 				-e "s@$n@<span class=\"n\">@g" -e "s@$o@<span class=\"o\">@g")
+	sed -i -e 's@old@เก่า@g'  -e 's@new@ใหม่@g' -e 's@words@คำ@g'\
+		-e 's@common@ตรงกัน@g' -e 's@deleted@ลบ   @g' -e 's@inserted@แทรก@g'\
+		-e 's@changed@เปลี่ยน@g' "$st"
 	cat <<EOF >"$3"
 <html lang="th">
 <head>
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
 <title>$1 / $2</title>
+EOF
+	((nojs)) || cat <<EOF >>"$3"
 <script type="application/javascript">
 //<![CDATA[<!--
 view=0;
@@ -71,6 +78,8 @@ window.onclick = function (){
 		for(i=0; i<s.length; i++) s[i].style.display="inline";}}
 //-->]]>
 </script>
+EOF
+	cat <<EOF >>"$3"
 <style type="text/css">
 body {background:$back; color:$font; font-size:150%; font-family:Arundina Serif,serif}
 h1 {text-align:center; font-size:80%}
@@ -80,25 +89,23 @@ span.n {color:$newf; background:$newp; text-decoration:underline}
 h1 span.o {padding:0 0.2em}
 h1 span.n {padding:0 0.2em}
 div.h {color:$hfont; background:$header; padding:0.2}
+div.no span.o {display:none !important}
+div.nn span.n {display:none !important}
 pre {margin-left:0.5em}
 div {background:$paper; padding:0.5em}
 </style>
 </head>
-<body title="Click to show: comparison / original / corrected&#013;คลิกเพื่อแสดง การเปรียบเทียบ / ต้นฉบับ / ฉบับแก้ไข">
-<div class="h">
-<h1><span class="o">$ai</span> <span class="n">$bi</span></h1>
-<pre>
-$(cat "$st" |sed  -e 's@old@เก่า@g'  -e 's@new@ใหม่@g' -e 's@words@คำ@g'\
-		-e 's@common@ตรงกัน@g' -e 's@deleted@ลบ   @g' -e 's@inserted@แทรก@g'\
-		-e 's@changed@เปลี่ยน@g')
-</pre>
-</div>
-<div>
-$ci
-</div>
-</body>
-</html>
 EOF
+	((nojs)) && echo '<body>' >>"$3" ||
+		echo '<body title="Click to show: comparison / original / corrected&#013;คลิกเพื่อแสดง การเปรียบเทียบ / ต้นฉบับ / ฉบับแก้ไข">' >>"$3"
+	echo -e "<div class=\"h\">\n<h1><span class=\"o\">$ai</span> <span class=\"n\">$bi</span></h1>\n<pre>\n$(cat "$st")\n</pre>\n</div>" >>"$3"
+	echo -e "<div>\n$ci\n</div>" >>"$3"
+	((nojs)) &&
+		echo -e "<hr /><div class=\"h nn\">\n<h1><span class=\"o\">$ai</span> <span class=\"n\">$bi</span></h1>\n<pre>\n$(head -1 "$st")\n</pre>\n</div>" >>"$3"
+		echo -e "<div class=\"nn\">\n$ci\n</div>" >>"$3" &&
+		echo -e "<hr /><div class=\"h no\">\n<h1><span class=\"o\">$ai</span> <span class=\"n\">$bi</span></h1>\n<pre>\n$(tail -1 "$st")\n</pre>\n</div>" >>"$3"
+		echo -e "<div class=\"no\">\n$ci\n</div>" >>"$3"
+	echo -e "</body>\n</html>" >>"$3"
 
 else  ## terminal
 	echo "$as" >"$at"
