Multiple subtitle selection possible

diff --git a/subs b/subs
--- a/subs
+++ b/subs
@@ -1,6 +1,7 @@
 #!/bin/bash
-set -vx
+set +vx
 ## subs: download subtitles from subscene.com
+## Usage: subs <search terms>
 ## Required: wget less/zenity unzip sed grep coreutils(rm)
 
 ## subtitles language -- see: https://subscene.com/filter/edit
@@ -14,9 +15,10 @@ Info(){ ## $1: Message
 	((zen)) && $zenity --info --text="$1" || echo "$1"
 }
 
-Error(){ ## $1: Message
+Error(){ ## $1: Message; $2: exit number
+	[[ $2 ]] && m="Exit: $1" || m=$1
 	((zen)) && $zenity --error --text="$1" || echo "$1"
-	exit $2
+	[[ $2 ]] && exit $2
 }
 
 Entry(){ ## $1: Message
@@ -120,37 +122,46 @@ done
 ((n==1)) && c=1 || {
 	if ((zen))
 	then
-		c=$($zlist --column=Subtitle --column=Filenumber $subtitlez)
+		c=$($zlist --column=Subtitle --column=Filenumber $subtitlez --multiple)
 	else
 		echo -e "$subtitles" |
-				less +Gg -~RXQFP"%pB\% %f press Q then enter number of subtitles file"
-		read -rp "Which subtitles file? " c
+				less +Gg -~RXQFP"%pB\% %f press Q then enter number of subtitles file (multiple by comma) "
+		read -rp "Which subtitles file? " cr
+		c=${cr//[^0-9]/|}
 	fi
 }
-[[ $c ]] && subtitle=${sltit[$c]}
-[[ -z $subtitle ]] && {
-	((zen)) && exit 9 || Error "Exit: no valid choice" 10
+[[ -z $c || $c != *[0-9]* ]] && {
+	((zen)) && exit 9 || Error "Exit: no valid input: $cr" 10
 }
 
-sfurl=$domain${slurl[$c]}
-sf="sf.$subtitle"
-((debug)) && echo "$sf $sfurl"
-[[ -f "$sf" ]] || $wget "$sf" "$sfurl"
+srts='Downloaded:\n'
+grep '|' <<<$c && number=1 || number=0
+for ci in ${c//|/ }
+do
+	subtitle=${sltit[$ci]}
+	[[ -z $subtitle ]] && Error "Invalid number $ci skipped" && next
+	sfurl=$domain${slurl[$ci]}
+	sf="sf.$subtitle"
+	((debug)) && echo "$sf $sfurl"
+	[[ -f "$sf" ]] || $wget "$sf" "$sfurl"
 
-szurl=$domain$(grep 'mac=' "$sf" |sed 's@^.*<a href="@@' |sed 's@\".*@@')
-((debug)) || rm -- "$sf"
+	szurl=$domain$(grep 'mac=' "$sf" |sed 's@^.*<a href="@@' |sed 's@\".*@@')
+	((debug)) || rm -- "$sf"
 
-sz="sz.$title$subtitle.zip"
-((debug)) && echo "$sz $szurl"
-$wget "$sz" "$szurl"
+	sz="sz.$title$subtitle.zip"
+	((debug)) && echo "$sz $szurl"
+	$wget "$sz" "$szurl"
 
-episode=$(grep -o '[Ss][0-9]*[Ee][0-9]*' <<<"$subtitle" |sed 's@[Ss]0*@@' |sed 's@[Ee]@x@')
-[[ $episode ]] && episode=" $episode"
-((addlang)) && al="_$lang"
-srt=$title$episode$al.srt
-unzip -p "$sz" >"$srt"
-((debug)) || rm -- "$sz"
+	episode=$(grep -o '[Ss][0-9]*[Ee][0-9]*' <<<"$subtitle" |sed 's@[Ss]0*@@' |sed 's@[Ee]@x@')
+	[[ $episode ]] && episode=" $episode"
+	((number)) && num=".${slurl[$ci]##*/}"
+	((addlang)) && al="_$lang"
+	srt=$title$episode$num$al.srt
+	unzip -p "$sz" >"$srt"
+	((debug)) || rm -- "$sz"
+	srts+="$srt\n"
+done
 
-Info "Downloaded: $srt"
+Info "$srts"
 
 exit 0
